### ISSUE TITLE
rails example

### ISSUE THREAD

**Issue by weepy** [mattly/rack-coffee#1]
Hi

Would you be able to explain how to add this to a Rails project ?

Thanks

J

**Comment by mattly** [comment]
well there's the bistrocar plugin that inspired this: http://github.com/jnicklas/bistro_car

otherwise I haven't played terribly much with the rails middleware stuff (my day job involves maintaining rails 2.2 apps, my other projects are all pure rack/sinatra), but I think it would be something like:

config.middleware.use Rack::Coffee, :root => "#{RAILS_ROOT}/public", :url => "/javascripts"

in your config.rb's initialization block, after you're required 'rack/coffee' of course.

Let me know if this works for you and I'll add it to the readme; elsewise I will hopefully have a chance to play with rails 3 over the weekend.

**Comment by weepy** [comment]
so this worked ok in environment.rb:

<pre>
  require "rack/coffee"
  config.middleware.use Rack::Coffee, :root => "#{RAILS_ROOT}/public"
</pre>

**Comment by mattly** [comment]
great, updated the documentation, thanks
