### ISSUE TITLE
Compress/minify JavaScript?

### ISSUE THREAD

**Issue by brainix** [mattly/rack-coffee#10]
I adore rack-coffee.  But is there any way you guys could implement some way to compress/minify JavaScript, e.g. using YUI or Google's Closure?

Feel free to close this issue as stupid, but just an idea!  Thanks!

**Comment by mattly** [comment]
@brainix well, feel free to submit a pull-request ;)

My vision for rack-coffee has always been about providing a tool to aid in the development process, with the idea that in production systems you will want to serve pre-compiled static files. Really it was something I put in my middleware stack at dev-time ahead of rack-static so that I didn't have to have "coffee -w -c -o ..." running in the background. 

Obviously, people are using it in production anyway.

An underlying philosophy is to do the least amount possible to facilitate these duties, and as you've stated, there are better tools out there for handling the compress/minify state. Which library is better? Do we make it a dependnecy? Etc. Heck, there might even be other rack middleware to minify outbound application/javascript data, and I know there are rack middleware to handle compression.

I'd be open to a configuration option where one could provide a lambda that would be run, given the compiled JS data  as an argument, that could handle this, and then let the library user choose their own minify/compress options, but I do have to wonder if there are other tools that can handle this in the appropriate spot in the middleware stack.
